language: objective-c
osx_image: xcode9.3beta
branches:
  only:
    - master
script: set -o pipefail && xcodebuild test -project Legacy.xcodeproj -scheme Legacy-iOS -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty
