templates:
    - ../Sources/Templates
output:
    Example-iOS/Generated
prune:
    true
verbose:
    true
project:
    file:
        Example-iOS.xcodeproj
    root:
        .
    target:
        name: Example-iOS
